package model.service;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import model.service.common.AppModule;

import model.view.MonthSearchVOImpl;
import model.view.PopulateStyleFromPreviousMonthVOImpl;
import model.view.PopulateStylesVOImpl;
import model.view.WpMonthListVOImpl;

import model.view.WpPlanningBoardVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 06 14:32:20 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    public void setSessionValues(String orgId, String userId, String respId,
                                 String respApplId) {  
        
    //      System.out.println("====================  set session values    ================================");
                
          orgId = "343";
          userId = "5219";

    //       System.out.println(" orgId "+ orgId  + "  data type  "+ orgId.getClass().getName());
    //
       
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession)ectx.getSession(false);
    
            if (orgId != null) {
                userSession.setAttribute("orgId", orgId);
            }
    
            if (userId != null) {
                userSession.setAttribute("userId", userId);
            }
    
            if (respId != null) {
                userSession.setAttribute("respId", respId);
            }
    
            if (respApplId != null) {
                userSession.setAttribute("respApplId", respApplId);
            }         
         
      }


    /**
     * Container's getter for OrgVO1.
     * @return OrgVO1
     */
    public ViewObjectImpl getOrgVO1() {
        return (ViewObjectImpl)findViewObject("OrgVO1");
    }

    /**
     * Container's getter for MonthSearchVO1.
     * @return MonthSearchVO1
     */
    public ViewObjectImpl getMonthSearchVO1() {
        return (ViewObjectImpl)findViewObject("MonthSearchVO1");
    }

    /**
     * Container's getter for WpMonthListVO1.
     * @return WpMonthListVO1
     */
    public ViewObjectImpl getWpMonthListVO1() {
        return (ViewObjectImpl)findViewObject("WpMonthListVO1");
    }

    /**
     * Container's getter for MonthSearchVO_vs_WpMonthListVO_vl1.
     * @return MonthSearchVO_vs_WpMonthListVO_vl1
     */
    public ViewLinkImpl getMonthSearchVO_vs_WpMonthListVO_vl1() {
        return (ViewLinkImpl)findViewLink("MonthSearchVO_vs_WpMonthListVO_vl1");
    }

    /**
     * Container's getter for WpHolidayCalendarVO1.
     * @return WpHolidayCalendarVO1
     */
    public ViewObjectImpl getWpHolidayCalendarVO1() {
        return (ViewObjectImpl)findViewObject("WpHolidayCalendarVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_WpHolidayCalendarVO_vl1.
     * @return WpMonthListVO_vs_WpHolidayCalendarVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_WpHolidayCalendarVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_WpHolidayCalendarVO_vl1");
    }


    /**
     * Container's getter for WpPlanningBoardVO1.
     * @return WpPlanningBoardVO1
     */
    public ViewObjectImpl getWpPlanningBoardVO1() {
        return (ViewObjectImpl)findViewObject("WpPlanningBoardVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_WpPlanningBoardVO_vl1.
     * @return WpMonthListVO_vs_WpPlanningBoardVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_WpPlanningBoardVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_WpPlanningBoardVO_vl1");
    }

    /**
     * Container's getter for WpPlanningBoardLoadVO1.
     * @return WpPlanningBoardLoadVO1
     */
    public ViewObjectImpl getWpPlanningBoardLoadVO1() {
        return (ViewObjectImpl)findViewObject("WpPlanningBoardLoadVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_WpPlanningBoardLoadVO_vl1.
     * @return WpMonthListVO_vs_WpPlanningBoardLoadVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_WpPlanningBoardLoadVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_WpPlanningBoardLoadVO_vl1");
    }

    /**
     * Container's getter for PopulateStylesVO1.
     * @return PopulateStylesVO1
     */
    public ViewObjectImpl getPopulateStylesVO1() {
        return (ViewObjectImpl)findViewObject("PopulateStylesVO1");
    }

    /**
     * Container's getter for OrgVO_vs_PopulateStyles_vl1.
     * @return OrgVO_vs_PopulateStyles_vl1
     */
    public ViewLinkImpl getOrgVO_vs_PopulateStyles_vl1() {
        return (ViewLinkImpl)findViewLink("OrgVO_vs_PopulateStyles_vl1");
    }

    /**
     * Container's getter for BuyerWiseMonthlyQtyVO1.
     * @return BuyerWiseMonthlyQtyVO1
     */
    public ViewObjectImpl getBuyerWiseMonthlyQtyVO1() {
        return (ViewObjectImpl)findViewObject("BuyerWiseMonthlyQtyVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_BuyerWiseMonthlyQtyVO_vl1.
     * @return WpMonthListVO_vs_BuyerWiseMonthlyQtyVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_BuyerWiseMonthlyQtyVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_BuyerWiseMonthlyQtyVO_vl1");
    }

    /**
     * Container's getter for ProductionUnitWiseMonthlyQtyVO1.
     * @return ProductionUnitWiseMonthlyQtyVO1
     */
    public ViewObjectImpl getProductionUnitWiseMonthlyQtyVO1() {
        return (ViewObjectImpl)findViewObject("ProductionUnitWiseMonthlyQtyVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_ProductionUnitWiseMonthlyQtyVO_vl1.
     * @return WpMonthListVO_vs_ProductionUnitWiseMonthlyQtyVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_ProductionUnitWiseMonthlyQtyVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_ProductionUnitWiseMonthlyQtyVO_vl1");
    }

    /**
     * Container's getter for WpPlanningBoardAllSectionLoadVO1.
     * @return WpPlanningBoardAllSectionLoadVO1
     */
    public ViewObjectImpl getWpPlanningBoardAllSectionLoadVO1() {
        return (ViewObjectImpl)findViewObject("WpPlanningBoardAllSectionLoadVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_WpPlanningBoardAllSectionLoad_vl1.
     * @return WpMonthListVO_vs_WpPlanningBoardAllSectionLoad_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_WpPlanningBoardAllSectionLoad_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_WpPlanningBoardAllSectionLoad_vl1");
    }

    /**
     * Container's getter for MonthWiseDailyProcessQtyVO1.
     * @return MonthWiseDailyProcessQtyVO1
     */
    public ViewObjectImpl getMonthWiseDailyProcessQtyVO1() {
        return (ViewObjectImpl)findViewObject("MonthWiseDailyProcessQtyVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_MonthWiseDailyProcessQtyVO_vl1.
     * @return WpMonthListVO_vs_MonthWiseDailyProcessQtyVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_MonthWiseDailyProcessQtyVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_MonthWiseDailyProcessQtyVO_vl1");
    }

    /**
     * Container's getter for PopulateStyleFromPreviousMonthVO1.
     * @return PopulateStyleFromPreviousMonthVO1
     */
    public ViewObjectImpl getPopulateStyleFromPreviousMonthVO1() {
        return (ViewObjectImpl)findViewObject("PopulateStyleFromPreviousMonthVO1");
    }

    /**
     * Container's getter for WpPlanningBoardFreezeVO1.
     * @return WpPlanningBoardFreezeVO1
     */
    public ViewObjectImpl getWpPlanningBoardFreezeVO1() {
        return (ViewObjectImpl)findViewObject("WpPlanningBoardFreezeVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_WpPlanningBoardFreezeVO_vl1.
     * @return WpMonthListVO_vs_WpPlanningBoardFreezeVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_WpPlanningBoardFreezeVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_WpPlanningBoardFreezeVO_vl1");
    }

    /**
     * Container's getter for WpPlanningBoardFreezeLoadVO1.
     * @return WpPlanningBoardFreezeLoadVO1
     */
    public ViewObjectImpl getWpPlanningBoardFreezeLoadVO1() {
        return (ViewObjectImpl)findViewObject("WpPlanningBoardFreezeLoadVO1");
    }

    /**
     * Container's getter for WpMonthListVO_vs_WpPlanningBoardFreezeLoadVO_vl1.
     * @return WpMonthListVO_vs_WpPlanningBoardFreezeLoadVO_vl1
     */
    public ViewLinkImpl getWpMonthListVO_vs_WpPlanningBoardFreezeLoadVO_vl1() {
        return (ViewLinkImpl)findViewLink("WpMonthListVO_vs_WpPlanningBoardFreezeLoadVO_vl1");
    }


    /**
     * Container's getter for StyleWiseMonthlyQtyVO1.
     * @return StyleWiseMonthlyQtyVO1
     */
    public ViewObjectImpl getStyleWiseMonthlyQtyVO1() {
        return (ViewObjectImpl)findViewObject("StyleWiseMonthlyQtyVO1");
    }

    /**
     * Container's getter for Buyer_Style_MonthlyQty_vl1.
     * @return Buyer_Style_MonthlyQty_vl1
     */
    public ViewLinkImpl getBuyer_Style_MonthlyQty_vl1() {
        return (ViewLinkImpl)findViewLink("Buyer_Style_MonthlyQty_vl1");
    }

    /**
     * Container's getter for StyleWiseShipmentVO1.
     * @return StyleWiseShipmentVO1
     */
    public ViewObjectImpl getStyleWiseShipmentVO1() {
        return (ViewObjectImpl)findViewObject("StyleWiseShipmentVO1");
    }

    /**
     * Container's getter for PlanningBoardVO_vs_StyleWiseShipmentVO_vl1.
     * @return PlanningBoardVO_vs_StyleWiseShipmentVO_vl1
     */
    public ViewLinkImpl getPlanningBoardVO_vs_StyleWiseShipmentVO_vl1() {
        return (ViewLinkImpl)findViewLink("PlanningBoardVO_vs_StyleWiseShipmentVO_vl1");
    }

    /**
     * Container's getter for StyleWiseSectionProcessSamVO1.
     * @return StyleWiseSectionProcessSamVO1
     */
    public ViewObjectImpl getStyleWiseSectionProcessSamVO1() {
        return (ViewObjectImpl)findViewObject("StyleWiseSectionProcessSamVO1");
    }

    /**
     * Container's getter for PlanningBoardVO_vs_StyleWiseSectionProcessSamVO_vl1.
     * @return PlanningBoardVO_vs_StyleWiseSectionProcessSamVO_vl1
     */
    public ViewLinkImpl getPlanningBoardVO_vs_StyleWiseSectionProcessSamVO_vl1() {
        return (ViewLinkImpl)findViewLink("PlanningBoardVO_vs_StyleWiseSectionProcessSamVO_vl1");
    }
}
