package model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 07 11:17:27 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpMonthListEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public WpMonthListEOCollImpl() {
    }
}
