package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 07 13:00:43 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpPlanningBoardEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        PlanningBoardId {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getPlanningBoardId();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setPlanningBoardId((Number)value);
            }
        }
        ,
        MonthId {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getMonthId();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setMonthId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getSystemId();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        D1 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD1();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD1((Number)value);
            }
        }
        ,
        D2 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD2();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD2((Number)value);
            }
        }
        ,
        D3 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD3();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD3((Number)value);
            }
        }
        ,
        D4 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD4();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD4((Number)value);
            }
        }
        ,
        D5 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD5();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD5((Number)value);
            }
        }
        ,
        D6 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD6();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD6((Number)value);
            }
        }
        ,
        D7 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD7();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD7((Number)value);
            }
        }
        ,
        D8 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD8();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD8((Number)value);
            }
        }
        ,
        D9 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD9();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD9((Number)value);
            }
        }
        ,
        D10 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD10();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD10((Number)value);
            }
        }
        ,
        D11 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD11();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD11((Number)value);
            }
        }
        ,
        D12 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD12();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD12((Number)value);
            }
        }
        ,
        D13 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD13();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD13((Number)value);
            }
        }
        ,
        D14 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD14();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD14((Number)value);
            }
        }
        ,
        D15 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD15();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD15((Number)value);
            }
        }
        ,
        D16 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD16();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD16((Number)value);
            }
        }
        ,
        D17 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD17();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD17((Number)value);
            }
        }
        ,
        D18 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD18();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD18((Number)value);
            }
        }
        ,
        D19 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD19();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD19((Number)value);
            }
        }
        ,
        D20 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD20();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD20((Number)value);
            }
        }
        ,
        D21 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD21();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD21((Number)value);
            }
        }
        ,
        D22 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD22();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD22((Number)value);
            }
        }
        ,
        D23 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD23();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD23((Number)value);
            }
        }
        ,
        D24 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD24();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD24((Number)value);
            }
        }
        ,
        D25 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD25();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD25((Number)value);
            }
        }
        ,
        D26 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD26();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD26((Number)value);
            }
        }
        ,
        D27 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD27();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD27((Number)value);
            }
        }
        ,
        D28 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD28();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD28((Number)value);
            }
        }
        ,
        D29 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD29();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD29((Number)value);
            }
        }
        ,
        D30 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD30();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD30((Number)value);
            }
        }
        ,
        D31 {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getD31();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setD31((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        WpMonthListEO {
            public Object get(WpPlanningBoardEOImpl obj) {
                return obj.getWpMonthListEO();
            }

            public void put(WpPlanningBoardEOImpl obj, Object value) {
                obj.setWpMonthListEO((WpMonthListEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpPlanningBoardEOImpl object);

        public abstract void put(WpPlanningBoardEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PLANNINGBOARDID = AttributesEnum.PlanningBoardId.index();
    public static final int MONTHID = AttributesEnum.MonthId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int D1 = AttributesEnum.D1.index();
    public static final int D2 = AttributesEnum.D2.index();
    public static final int D3 = AttributesEnum.D3.index();
    public static final int D4 = AttributesEnum.D4.index();
    public static final int D5 = AttributesEnum.D5.index();
    public static final int D6 = AttributesEnum.D6.index();
    public static final int D7 = AttributesEnum.D7.index();
    public static final int D8 = AttributesEnum.D8.index();
    public static final int D9 = AttributesEnum.D9.index();
    public static final int D10 = AttributesEnum.D10.index();
    public static final int D11 = AttributesEnum.D11.index();
    public static final int D12 = AttributesEnum.D12.index();
    public static final int D13 = AttributesEnum.D13.index();
    public static final int D14 = AttributesEnum.D14.index();
    public static final int D15 = AttributesEnum.D15.index();
    public static final int D16 = AttributesEnum.D16.index();
    public static final int D17 = AttributesEnum.D17.index();
    public static final int D18 = AttributesEnum.D18.index();
    public static final int D19 = AttributesEnum.D19.index();
    public static final int D20 = AttributesEnum.D20.index();
    public static final int D21 = AttributesEnum.D21.index();
    public static final int D22 = AttributesEnum.D22.index();
    public static final int D23 = AttributesEnum.D23.index();
    public static final int D24 = AttributesEnum.D24.index();
    public static final int D25 = AttributesEnum.D25.index();
    public static final int D26 = AttributesEnum.D26.index();
    public static final int D27 = AttributesEnum.D27.index();
    public static final int D28 = AttributesEnum.D28.index();
    public static final int D29 = AttributesEnum.D29.index();
    public static final int D30 = AttributesEnum.D30.index();
    public static final int D31 = AttributesEnum.D31.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int WPMONTHLISTEO = AttributesEnum.WpMonthListEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpPlanningBoardEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.WpPlanningBoardEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for PlanningBoardId, using the alias name PlanningBoardId.
     * @return the PlanningBoardId
     */
    public Number getPlanningBoardId() {
        return (Number)getAttributeInternal(PLANNINGBOARDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanningBoardId.
     * @param value value to set the PlanningBoardId
     */
    public void setPlanningBoardId(Number value) {
        setAttributeInternal(PLANNINGBOARDID, value);
    }

    /**
     * Gets the attribute value for MonthId, using the alias name MonthId.
     * @return the MonthId
     */
    public Number getMonthId() {
        return (Number)getAttributeInternal(MONTHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MonthId.
     * @param value value to set the MonthId
     */
    public void setMonthId(Number value) {
        setAttributeInternal(MONTHID, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for D1, using the alias name D1.
     * @return the D1
     */
    public Number getD1() {
        return (Number)getAttributeInternal(D1);
    }

    /**
     * Sets <code>value</code> as the attribute value for D1.
     * @param value value to set the D1
     */
    public void setD1(Number value) {
        setAttributeInternal(D1, value);
    }

    /**
     * Gets the attribute value for D2, using the alias name D2.
     * @return the D2
     */
    public Number getD2() {
        return (Number)getAttributeInternal(D2);
    }

    /**
     * Sets <code>value</code> as the attribute value for D2.
     * @param value value to set the D2
     */
    public void setD2(Number value) {
        setAttributeInternal(D2, value);
    }

    /**
     * Gets the attribute value for D3, using the alias name D3.
     * @return the D3
     */
    public Number getD3() {
        return (Number)getAttributeInternal(D3);
    }

    /**
     * Sets <code>value</code> as the attribute value for D3.
     * @param value value to set the D3
     */
    public void setD3(Number value) {
        setAttributeInternal(D3, value);
    }

    /**
     * Gets the attribute value for D4, using the alias name D4.
     * @return the D4
     */
    public Number getD4() {
        return (Number)getAttributeInternal(D4);
    }

    /**
     * Sets <code>value</code> as the attribute value for D4.
     * @param value value to set the D4
     */
    public void setD4(Number value) {
        setAttributeInternal(D4, value);
    }

    /**
     * Gets the attribute value for D5, using the alias name D5.
     * @return the D5
     */
    public Number getD5() {
        return (Number)getAttributeInternal(D5);
    }

    /**
     * Sets <code>value</code> as the attribute value for D5.
     * @param value value to set the D5
     */
    public void setD5(Number value) {
        setAttributeInternal(D5, value);
    }

    /**
     * Gets the attribute value for D6, using the alias name D6.
     * @return the D6
     */
    public Number getD6() {
        return (Number)getAttributeInternal(D6);
    }

    /**
     * Sets <code>value</code> as the attribute value for D6.
     * @param value value to set the D6
     */
    public void setD6(Number value) {
        setAttributeInternal(D6, value);
    }

    /**
     * Gets the attribute value for D7, using the alias name D7.
     * @return the D7
     */
    public Number getD7() {
        return (Number)getAttributeInternal(D7);
    }

    /**
     * Sets <code>value</code> as the attribute value for D7.
     * @param value value to set the D7
     */
    public void setD7(Number value) {
        setAttributeInternal(D7, value);
    }

    /**
     * Gets the attribute value for D8, using the alias name D8.
     * @return the D8
     */
    public Number getD8() {
        return (Number)getAttributeInternal(D8);
    }

    /**
     * Sets <code>value</code> as the attribute value for D8.
     * @param value value to set the D8
     */
    public void setD8(Number value) {
        setAttributeInternal(D8, value);
    }

    /**
     * Gets the attribute value for D9, using the alias name D9.
     * @return the D9
     */
    public Number getD9() {
        return (Number)getAttributeInternal(D9);
    }

    /**
     * Sets <code>value</code> as the attribute value for D9.
     * @param value value to set the D9
     */
    public void setD9(Number value) {
        setAttributeInternal(D9, value);
    }

    /**
     * Gets the attribute value for D10, using the alias name D10.
     * @return the D10
     */
    public Number getD10() {
        return (Number)getAttributeInternal(D10);
    }

    /**
     * Sets <code>value</code> as the attribute value for D10.
     * @param value value to set the D10
     */
    public void setD10(Number value) {
        setAttributeInternal(D10, value);
    }

    /**
     * Gets the attribute value for D11, using the alias name D11.
     * @return the D11
     */
    public Number getD11() {
        return (Number)getAttributeInternal(D11);
    }

    /**
     * Sets <code>value</code> as the attribute value for D11.
     * @param value value to set the D11
     */
    public void setD11(Number value) {
        setAttributeInternal(D11, value);
    }

    /**
     * Gets the attribute value for D12, using the alias name D12.
     * @return the D12
     */
    public Number getD12() {
        return (Number)getAttributeInternal(D12);
    }

    /**
     * Sets <code>value</code> as the attribute value for D12.
     * @param value value to set the D12
     */
    public void setD12(Number value) {
        setAttributeInternal(D12, value);
    }

    /**
     * Gets the attribute value for D13, using the alias name D13.
     * @return the D13
     */
    public Number getD13() {
        return (Number)getAttributeInternal(D13);
    }

    /**
     * Sets <code>value</code> as the attribute value for D13.
     * @param value value to set the D13
     */
    public void setD13(Number value) {
        setAttributeInternal(D13, value);
    }

    /**
     * Gets the attribute value for D14, using the alias name D14.
     * @return the D14
     */
    public Number getD14() {
        return (Number)getAttributeInternal(D14);
    }

    /**
     * Sets <code>value</code> as the attribute value for D14.
     * @param value value to set the D14
     */
    public void setD14(Number value) {
        setAttributeInternal(D14, value);
    }

    /**
     * Gets the attribute value for D15, using the alias name D15.
     * @return the D15
     */
    public Number getD15() {
        return (Number)getAttributeInternal(D15);
    }

    /**
     * Sets <code>value</code> as the attribute value for D15.
     * @param value value to set the D15
     */
    public void setD15(Number value) {
        setAttributeInternal(D15, value);
    }

    /**
     * Gets the attribute value for D16, using the alias name D16.
     * @return the D16
     */
    public Number getD16() {
        return (Number)getAttributeInternal(D16);
    }

    /**
     * Sets <code>value</code> as the attribute value for D16.
     * @param value value to set the D16
     */
    public void setD16(Number value) {
        setAttributeInternal(D16, value);
    }

    /**
     * Gets the attribute value for D17, using the alias name D17.
     * @return the D17
     */
    public Number getD17() {
        return (Number)getAttributeInternal(D17);
    }

    /**
     * Sets <code>value</code> as the attribute value for D17.
     * @param value value to set the D17
     */
    public void setD17(Number value) {
        setAttributeInternal(D17, value);
    }

    /**
     * Gets the attribute value for D18, using the alias name D18.
     * @return the D18
     */
    public Number getD18() {
        return (Number)getAttributeInternal(D18);
    }

    /**
     * Sets <code>value</code> as the attribute value for D18.
     * @param value value to set the D18
     */
    public void setD18(Number value) {
        setAttributeInternal(D18, value);
    }

    /**
     * Gets the attribute value for D19, using the alias name D19.
     * @return the D19
     */
    public Number getD19() {
        return (Number)getAttributeInternal(D19);
    }

    /**
     * Sets <code>value</code> as the attribute value for D19.
     * @param value value to set the D19
     */
    public void setD19(Number value) {
        setAttributeInternal(D19, value);
    }

    /**
     * Gets the attribute value for D20, using the alias name D20.
     * @return the D20
     */
    public Number getD20() {
        return (Number)getAttributeInternal(D20);
    }

    /**
     * Sets <code>value</code> as the attribute value for D20.
     * @param value value to set the D20
     */
    public void setD20(Number value) {
        setAttributeInternal(D20, value);
    }

    /**
     * Gets the attribute value for D21, using the alias name D21.
     * @return the D21
     */
    public Number getD21() {
        return (Number)getAttributeInternal(D21);
    }

    /**
     * Sets <code>value</code> as the attribute value for D21.
     * @param value value to set the D21
     */
    public void setD21(Number value) {
        setAttributeInternal(D21, value);
    }

    /**
     * Gets the attribute value for D22, using the alias name D22.
     * @return the D22
     */
    public Number getD22() {
        return (Number)getAttributeInternal(D22);
    }

    /**
     * Sets <code>value</code> as the attribute value for D22.
     * @param value value to set the D22
     */
    public void setD22(Number value) {
        setAttributeInternal(D22, value);
    }

    /**
     * Gets the attribute value for D23, using the alias name D23.
     * @return the D23
     */
    public Number getD23() {
        return (Number)getAttributeInternal(D23);
    }

    /**
     * Sets <code>value</code> as the attribute value for D23.
     * @param value value to set the D23
     */
    public void setD23(Number value) {
        setAttributeInternal(D23, value);
    }

    /**
     * Gets the attribute value for D24, using the alias name D24.
     * @return the D24
     */
    public Number getD24() {
        return (Number)getAttributeInternal(D24);
    }

    /**
     * Sets <code>value</code> as the attribute value for D24.
     * @param value value to set the D24
     */
    public void setD24(Number value) {
        setAttributeInternal(D24, value);
    }

    /**
     * Gets the attribute value for D25, using the alias name D25.
     * @return the D25
     */
    public Number getD25() {
        return (Number)getAttributeInternal(D25);
    }

    /**
     * Sets <code>value</code> as the attribute value for D25.
     * @param value value to set the D25
     */
    public void setD25(Number value) {
        setAttributeInternal(D25, value);
    }

    /**
     * Gets the attribute value for D26, using the alias name D26.
     * @return the D26
     */
    public Number getD26() {
        return (Number)getAttributeInternal(D26);
    }

    /**
     * Sets <code>value</code> as the attribute value for D26.
     * @param value value to set the D26
     */
    public void setD26(Number value) {
        setAttributeInternal(D26, value);
    }

    /**
     * Gets the attribute value for D27, using the alias name D27.
     * @return the D27
     */
    public Number getD27() {
        return (Number)getAttributeInternal(D27);
    }

    /**
     * Sets <code>value</code> as the attribute value for D27.
     * @param value value to set the D27
     */
    public void setD27(Number value) {
        setAttributeInternal(D27, value);
    }

    /**
     * Gets the attribute value for D28, using the alias name D28.
     * @return the D28
     */
    public Number getD28() {
        return (Number)getAttributeInternal(D28);
    }

    /**
     * Sets <code>value</code> as the attribute value for D28.
     * @param value value to set the D28
     */
    public void setD28(Number value) {
        setAttributeInternal(D28, value);
    }

    /**
     * Gets the attribute value for D29, using the alias name D29.
     * @return the D29
     */
    public Number getD29() {
        return (Number)getAttributeInternal(D29);
    }

    /**
     * Sets <code>value</code> as the attribute value for D29.
     * @param value value to set the D29
     */
    public void setD29(Number value) {
        setAttributeInternal(D29, value);
    }

    /**
     * Gets the attribute value for D30, using the alias name D30.
     * @return the D30
     */
    public Number getD30() {
        return (Number)getAttributeInternal(D30);
    }

    /**
     * Sets <code>value</code> as the attribute value for D30.
     * @param value value to set the D30
     */
    public void setD30(Number value) {
        setAttributeInternal(D30, value);
    }


    /**
     * Gets the attribute value for D31, using the alias name D31.
     * @return the D31
     */
    public Number getD31() {
        return (Number)getAttributeInternal(D31);
    }

    /**
     * Sets <code>value</code> as the attribute value for D31.
     * @param value value to set the D31
     */
    public void setD31(Number value) {
        setAttributeInternal(D31, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity WpMonthListEOImpl.
     */
    public WpMonthListEOImpl getWpMonthListEO() {
        return (WpMonthListEOImpl)getAttributeInternal(WPMONTHLISTEO);
    }

    /**
     * Sets <code>value</code> as the associated entity WpMonthListEOImpl.
     */
    public void setWpMonthListEO(WpMonthListEOImpl value) {
        setAttributeInternal(WPMONTHLISTEO, value);
    }


    /**
     * @param planningBoardId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number planningBoardId) {
        return new Key(new Object[]{planningBoardId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
        new oracle.jbo.server.SequenceImpl("WP_PLANNING_BOARD_SEQ",  getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        this.setPlanningBoardId(sVal);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
             String user = (String)sessionScope.get("userId");
             
        //        System.out.println("Document No -->" + getSrNoString());
              
             if (DML_UPDATE == operation) {
                 try {
                     setLastUpdatedDate((Date)Date.getCurrentDate());
                     setLastUpdatedBy(new oracle.jbo.domain.Number(user));              
                     
                 } catch (SQLException f) {
                     f.printStackTrace();
                 }
             } else if (DML_INSERT == operation) {

                 try {
                   
                     setCreationDate((Date)Date.getCurrentDate());
                     setCreatedBy(new oracle.jbo.domain.Number(user));

                 } catch (SQLException f) {
                     f.printStackTrace();
                 }
             }        super.doDML(operation, e);
    }
}
