package model.view;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 03 11:48:03 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateStyleFromPreviousMonthVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        MonthId {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getMonthId();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setMonthId((Number)value);
            }
        }
        ,
        MonthNumber {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getMonthNumber();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setMonthNumber((Number)value);
            }
        }
        ,
        MonthName {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getMonthName();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setMonthName((String)value);
            }
        }
        ,
        Year {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getYear();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setYear((Number)value);
            }
        }
        ,
        MonthSerial {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getMonthSerial();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setMonthSerial((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        OrgId {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        OrderQty {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        MonthlyTotal {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getMonthlyTotal();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setMonthlyTotal((Number)value);
            }
        }
        ,
        PrevMonthsQty {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getPrevMonthsQty();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setPrevMonthsQty((Number)value);
            }
        }
        ,
        RemainingQty {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getRemainingQty();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setRemainingQty((Number)value);
            }
        }
        ,
        LastDayQty {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getLastDayQty();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setLastDayQty((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BuyerName {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        Season {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Style {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Color {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getColor();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        WashName {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getWashName();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        CurrentSamVersion {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getCurrentSamVersion();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setCurrentSamVersion((Number)value);
            }
        }
        ,
        AvailableSamVersion {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getAvailableSamVersion();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setAvailableSamVersion((Number)value);
            }
        }
        ,
        StyleSetupId {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getStyleSetupId();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setStyleSetupId((Number)value);
            }
        }
        ,
        ProductionUnitShortName {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getProductionUnitShortName();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setProductionUnitShortName((String)value);
            }
        }
        ,
        PrevStyleCheckBox {
            public Object get(PopulateStyleFromPreviousMonthVORowImpl obj) {
                return obj.getPrevStyleCheckBox();
            }

            public void put(PopulateStyleFromPreviousMonthVORowImpl obj,
                            Object value) {
                obj.setPrevStyleCheckBox((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PopulateStyleFromPreviousMonthVORowImpl object);

        public abstract void put(PopulateStyleFromPreviousMonthVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MONTHID = AttributesEnum.MonthId.index();
    public static final int MONTHNUMBER = AttributesEnum.MonthNumber.index();
    public static final int MONTHNAME = AttributesEnum.MonthName.index();
    public static final int YEAR = AttributesEnum.Year.index();
    public static final int MONTHSERIAL = AttributesEnum.MonthSerial.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int MONTHLYTOTAL = AttributesEnum.MonthlyTotal.index();
    public static final int PREVMONTHSQTY = AttributesEnum.PrevMonthsQty.index();
    public static final int REMAININGQTY = AttributesEnum.RemainingQty.index();
    public static final int LASTDAYQTY = AttributesEnum.LastDayQty.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int CURRENTSAMVERSION = AttributesEnum.CurrentSamVersion.index();
    public static final int AVAILABLESAMVERSION = AttributesEnum.AvailableSamVersion.index();
    public static final int STYLESETUPID = AttributesEnum.StyleSetupId.index();
    public static final int PRODUCTIONUNITSHORTNAME = AttributesEnum.ProductionUnitShortName.index();
    public static final int PREVSTYLECHECKBOX = AttributesEnum.PrevStyleCheckBox.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PopulateStyleFromPreviousMonthVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute MonthId.
     * @return the MonthId
     */
    public Number getMonthId() {
        return (Number) getAttributeInternal(MONTHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthId.
     * @param value value to set the  MonthId
     */
    public void setMonthId(Number value) {
        setAttributeInternal(MONTHID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthNumber.
     * @return the MonthNumber
     */
    public Number getMonthNumber() {
        return (Number) getAttributeInternal(MONTHNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthNumber.
     * @param value value to set the  MonthNumber
     */
    public void setMonthNumber(Number value) {
        setAttributeInternal(MONTHNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthName.
     * @return the MonthName
     */
    public String getMonthName() {
        return (String) getAttributeInternal(MONTHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthName.
     * @param value value to set the  MonthName
     */
    public void setMonthName(String value) {
        setAttributeInternal(MONTHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Year.
     * @return the Year
     */
    public Number getYear() {
        return (Number) getAttributeInternal(YEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Year.
     * @param value value to set the  Year
     */
    public void setYear(Number value) {
        setAttributeInternal(YEAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthSerial.
     * @return the MonthSerial
     */
    public Number getMonthSerial() {
        return (Number) getAttributeInternal(MONTHSERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthSerial.
     * @param value value to set the  MonthSerial
     */
    public void setMonthSerial(Number value) {
        setAttributeInternal(MONTHSERIAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SystemId.
     * @param value value to set the  SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Remarks.
     * @param value value to set the  Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
     * @param value value to set the  OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderQty.
     * @param value value to set the  OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthlyTotal.
     * @return the MonthlyTotal
     */
    public Number getMonthlyTotal() {
        return (Number) getAttributeInternal(MONTHLYTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthlyTotal.
     * @param value value to set the  MonthlyTotal
     */
    public void setMonthlyTotal(Number value) {
        setAttributeInternal(MONTHLYTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrevMonthsQty.
     * @return the PrevMonthsQty
     */
    public Number getPrevMonthsQty() {
        return (Number) getAttributeInternal(PREVMONTHSQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrevMonthsQty.
     * @param value value to set the  PrevMonthsQty
     */
    public void setPrevMonthsQty(Number value) {
        setAttributeInternal(PREVMONTHSQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemainingQty.
     * @return the RemainingQty
     */
    public Number getRemainingQty() {
        return (Number) getAttributeInternal(REMAININGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemainingQty.
     * @param value value to set the  RemainingQty
     */
    public void setRemainingQty(Number value) {
        setAttributeInternal(REMAININGQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastDayQty.
     * @return the LastDayQty
     */
    public Number getLastDayQty() {
        return (Number) getAttributeInternal(LASTDAYQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastDayQty.
     * @param value value to set the  LastDayQty
     */
    public void setLastDayQty(Number value) {
        setAttributeInternal(LASTDAYQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Color.
     * @return the Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color.
     * @param value value to set the  Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WashName.
     * @return the WashName
     */
    public String getWashName() {
        return (String) getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WashName.
     * @param value value to set the  WashName
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSamVersion.
     * @return the CurrentSamVersion
     */
    public Number getCurrentSamVersion() {
        return (Number) getAttributeInternal(CURRENTSAMVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSamVersion.
     * @param value value to set the  CurrentSamVersion
     */
    public void setCurrentSamVersion(Number value) {
        setAttributeInternal(CURRENTSAMVERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AvailableSamVersion.
     * @return the AvailableSamVersion
     */
    public Number getAvailableSamVersion() {
        return (Number) getAttributeInternal(AVAILABLESAMVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AvailableSamVersion.
     * @param value value to set the  AvailableSamVersion
     */
    public void setAvailableSamVersion(Number value) {
        setAttributeInternal(AVAILABLESAMVERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleSetupId.
     * @return the StyleSetupId
     */
    public Number getStyleSetupId() {
        return (Number) getAttributeInternal(STYLESETUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleSetupId.
     * @param value value to set the  StyleSetupId
     */
    public void setStyleSetupId(Number value) {
        setAttributeInternal(STYLESETUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductionUnitShortName.
     * @return the ProductionUnitShortName
     */
    public String getProductionUnitShortName() {
        return (String) getAttributeInternal(PRODUCTIONUNITSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductionUnitShortName.
     * @param value value to set the  ProductionUnitShortName
     */
    public void setProductionUnitShortName(String value) {
        setAttributeInternal(PRODUCTIONUNITSHORTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrevStyleCheckBox.
     * @return the PrevStyleCheckBox
     */
    public String getPrevStyleCheckBox() {
      
        return (String) getAttributeInternal(PREVSTYLECHECKBOX);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrevStyleCheckBox.
     * @param value value to set the  PrevStyleCheckBox
     */
    public void setPrevStyleCheckBox(String value) {
        setAttributeInternal(PREVSTYLECHECKBOX, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
