package model.view;

import java.sql.CallableStatement;

import model.entity.WpMonthListEOImpl;

import model.service.AppModuleImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCDataControl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 07 10:51:08 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpMonthListVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        MonthId {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthId();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthId((Number)value);
            }
        }
        ,
        MonthName {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthName();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthName((String)value);
            }
        }
        ,
        Year {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getYear();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setYear((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        WeeklyHoliday {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWeeklyHoliday();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setWeeklyHoliday((String)value);
            }
        }
        ,
        NumberOfDays {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getNumberOfDays();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setNumberOfDays((Number)value);
            }
        }
        ,
        MonthSearchVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthSearchVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpPlanningBoardVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpPlanningBoardVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpPlanningBoardLoadVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpPlanningBoardLoadVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpHolidayCalendarVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpHolidayCalendarVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpMonthListVORowImpl object);

        public abstract void put(WpMonthListVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MONTHID = AttributesEnum.MonthId.index();
    public static final int MONTHNAME = AttributesEnum.MonthName.index();
    public static final int YEAR = AttributesEnum.Year.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int WEEKLYHOLIDAY = AttributesEnum.WeeklyHoliday.index();
    public static final int NUMBEROFDAYS = AttributesEnum.NumberOfDays.index();
    public static final int MONTHSEARCHVO = AttributesEnum.MonthSearchVO.index();
    public static final int WPPLANNINGBOARDVO = AttributesEnum.WpPlanningBoardVO.index();
    public static final int WPPLANNINGBOARDLOADVO = AttributesEnum.WpPlanningBoardLoadVO.index();
    public static final int WPHOLIDAYCALENDARVO = AttributesEnum.WpHolidayCalendarVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpMonthListVORowImpl() {
    }
    AppModuleImpl appM = getAppModuleImpl();

    public AppModuleImpl getAppModuleImpl() {
        DCBindingContainer bindingContainer =
            (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
        //BindingContext bindingContext = BindingContext.getCurrent();
        DCDataControl dc =
            bindingContainer.findDataControl("AppModuleDataControl"); // Name of application module in datacontrolBinding.cpx
        AppModuleImpl appM = (AppModuleImpl)dc.getDataProvider();
        return appM;
    }

    /**
     * Gets WpMonthListEO entity object.
     * @return the WpMonthListEO
     */
    public WpMonthListEOImpl getWpMonthListEO() {
        return (WpMonthListEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for MONTH_ID using the alias name MonthId.
     * @return the MONTH_ID
     */
    public Number getMonthId() {
        return (Number) getAttributeInternal(MONTHID);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_ID using the alias name MonthId.
     * @param value value to set the MONTH_ID
     */
    public void setMonthId(Number value) {
        setAttributeInternal(MONTHID, value);
    }

    /**
     * Gets the attribute value for MONTH_NAME using the alias name MonthName.
     * @return the MONTH_NAME
     */
    public String getMonthName() {
        return (String) getAttributeInternal(MONTHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_NAME using the alias name MonthName.
     * @param value value to set the MONTH_NAME
     */
    public void setMonthName(String value) {
        setAttributeInternal(MONTHNAME, value);
    }

    /**
     * Gets the attribute value for YEAR using the alias name Year.
     * @return the YEAR
     */
    public Number getYear() {
        return (Number) getAttributeInternal(YEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR using the alias name Year.
     * @param value value to set the YEAR
     */
    public void setYear(Number value) {
        setAttributeInternal(YEAR, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for WEEKLY_HOLIDAY using the alias name WeeklyHoliday.
     * @return the WEEKLY_HOLIDAY
     */
    public String getWeeklyHoliday() {
        return (String) getAttributeInternal(WEEKLYHOLIDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEKLY_HOLIDAY using the alias name WeeklyHoliday.
     * @param value value to set the WEEKLY_HOLIDAY
     */
    public void setWeeklyHoliday(String value) {
        setAttributeInternal(WEEKLYHOLIDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NumberOfDays.
     * @return the NumberOfDays
     */
    public Number getNumberOfDays() {
        return (Number) getAttributeInternal(NUMBEROFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NumberOfDays.
     * @param value value to set the  NumberOfDays
     */
    public void setNumberOfDays(Number value) {
        setAttributeInternal(NUMBEROFDAYS, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link MonthSearchVO.
     */
    public Row getMonthSearchVO() {
        return (Row)getAttributeInternal(MONTHSEARCHVO);
    }

    /**
     * Sets the master-detail link MonthSearchVO between this object and <code>value</code>.
     */
    public void setMonthSearchVO(Row value) {
        setAttributeInternal(MONTHSEARCHVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpPlanningBoardVO.
     */
    public RowIterator getWpPlanningBoardVO() {
        return (RowIterator)getAttributeInternal(WPPLANNINGBOARDVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpPlanningBoardLoadVO.
     */
    public RowIterator getWpPlanningBoardLoadVO() {
        return (RowIterator)getAttributeInternal(WPPLANNINGBOARDLOADVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpHolidayCalendarVO.
     */
    public RowIterator getWpHolidayCalendarVO() {
        return (RowIterator)getAttributeInternal(WPHOLIDAYCALENDARVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    public void  updateLoadRowEntry(){
        String currentMonthId = this.getMonthId().toString();          
        String statement = "BEGIN APPS.WP_UPDATE_LOAD_ROW_ENTRY(:1); END;";
        CallableStatement cs =  appM.getDBTransaction().createCallableStatement(statement, 1);
          
        try {
            cs.setInt(1, Integer.parseInt(currentMonthId));
            cs.execute();
        }
        catch(Exception e){
           e.printStackTrace() ;
        }    
        
    }
}
