package model.view;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 12 12:33:16 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpMonthListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WpMonthListVOImpl() {
    }
    
    @Override
    public Row getCurrentRow() {
       if(super.getCurrentRow() == null) {       
           
           super.setCurrentRow(super.first());
       
       }
       
       return super.getCurrentRow();
       
    }
    
}
