package model.view;

import java.sql.CallableStatement;

import model.entity.WpMonthListEOImpl;

import model.service.AppModuleImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCDataControl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 12 12:31:31 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpMonthListVORowImpl extends ViewRowImpl {
    
    
    private Number getTotalforAttribute(String string) {
       Number qtySum = new Number(0);
       RowIterator rs =  this.getWpPlanningBoardVO();
       Row r;
       while(rs.hasNext()){
        r = rs.next();
         
         if(r.getAttribute(string) != null){
             qtySum = qtySum.add((Number)r.getAttribute(string));
         }
    
         
       }
     
        return qtySum;
       
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        MonthId {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthId();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthId((Number)value);
            }
        }
        ,
        MonthName {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthName();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthName((String)value);
            }
        }
        ,
        Year {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getYear();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setYear((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        WeeklyHoliday {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWeeklyHoliday();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setWeeklyHoliday((String)value);
            }
        }
        ,
        MonthNumber {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthNumber();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthNumber((Number)value);
            }
        }
        ,
        MonthSerial {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthSerial();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthSerial((Number)value);
            }
        }
        ,
        NumberOfDays {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getNumberOfDays();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setNumberOfDays((Number)value);
            }
        }
        ,
        WorkingdayCount {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWorkingdayCount();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setWorkingdayCount((Number)value);
            }
        }
        ,
        HolidayCount {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getHolidayCount();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setHolidayCount((Number)value);
            }
        }
        ,
        D1Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD1Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD1Total((Number)value);
            }
        }
        ,
        D2Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD2Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD2Total((Number)value);
            }
        }
        ,
        D3Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD3Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD3Total((Number)value);
            }
        }
        ,
        D4Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD4Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD4Total((Number)value);
            }
        }
        ,
        D5Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD5Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD5Total((Number)value);
            }
        }
        ,
        D6Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD6Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD6Total((Number)value);
            }
        }
        ,
        D7Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD7Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD7Total((Number)value);
            }
        }
        ,
        D8Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD8Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD8Total((Number)value);
            }
        }
        ,
        D9Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD9Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD9Total((Number)value);
            }
        }
        ,
        D10Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD10Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD10Total((Number)value);
            }
        }
        ,
        D11Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD11Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD11Total((Number)value);
            }
        }
        ,
        D12Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD12Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD12Total((Number)value);
            }
        }
        ,
        D13Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD13Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD13Total((Number)value);
            }
        }
        ,
        D14Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD14Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD14Total((Number)value);
            }
        }
        ,
        D15Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD15Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD15Total((Number)value);
            }
        }
        ,
        D16Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD16Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD16Total((Number)value);
            }
        }
        ,
        D17Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD17Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD17Total((Number)value);
            }
        }
        ,
        D18Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD18Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD18Total((Number)value);
            }
        }
        ,
        D19Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD19Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD19Total((Number)value);
            }
        }
        ,
        D20Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD20Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD20Total((Number)value);
            }
        }
        ,
        D21Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD21Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD21Total((Number)value);
            }
        }
        ,
        D22Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD22Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD22Total((Number)value);
            }
        }
        ,
        D23Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD23Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD23Total((Number)value);
            }
        }
        ,
        D24Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD24Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD24Total((Number)value);
            }
        }
        ,
        D25Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD25Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD25Total((Number)value);
            }
        }
        ,
        D26Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD26Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD26Total((Number)value);
            }
        }
        ,
        D27Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD27Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD27Total((Number)value);
            }
        }
        ,
        D28Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD28Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD28Total((Number)value);
            }
        }
        ,
        D29Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD29Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD29Total((Number)value);
            }
        }
        ,
        D30Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD30Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD30Total((Number)value);
            }
        }
        ,
        D31Total {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getD31Total();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setD31Total((Number)value);
            }
        }
        ,
        MonthlyGrandTotal {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthlyGrandTotal();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setMonthlyGrandTotal((Number)value);
            }
        }
        ,
        AveragePerDay {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getAveragePerDay();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAveragePerDay((Number)value);
            }
        }
        ,
        MonthSearchVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthSearchVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpPlanningBoardVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpPlanningBoardVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpPlanningBoardLoadVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpPlanningBoardLoadVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpHolidayCalendarVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpHolidayCalendarVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerWiseMonthlyQtyVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getBuyerWiseMonthlyQtyVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductionUnitWiseMonthlyQtyVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getProductionUnitWiseMonthlyQtyVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WpPlanningBoardAllSectionLoadVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getWpPlanningBoardAllSectionLoadVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MonthWiseDailyProcessQtyVO {
            public Object get(WpMonthListVORowImpl obj) {
                return obj.getMonthWiseDailyProcessQtyVO();
            }

            public void put(WpMonthListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpMonthListVORowImpl object);

        public abstract void put(WpMonthListVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MONTHID = AttributesEnum.MonthId.index();
    public static final int MONTHNAME = AttributesEnum.MonthName.index();
    public static final int YEAR = AttributesEnum.Year.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int WEEKLYHOLIDAY = AttributesEnum.WeeklyHoliday.index();
    public static final int MONTHNUMBER = AttributesEnum.MonthNumber.index();
    public static final int MONTHSERIAL = AttributesEnum.MonthSerial.index();
    public static final int NUMBEROFDAYS = AttributesEnum.NumberOfDays.index();
    public static final int WORKINGDAYCOUNT = AttributesEnum.WorkingdayCount.index();
    public static final int HOLIDAYCOUNT = AttributesEnum.HolidayCount.index();
    public static final int D1TOTAL = AttributesEnum.D1Total.index();
    public static final int D2TOTAL = AttributesEnum.D2Total.index();
    public static final int D3TOTAL = AttributesEnum.D3Total.index();
    public static final int D4TOTAL = AttributesEnum.D4Total.index();
    public static final int D5TOTAL = AttributesEnum.D5Total.index();
    public static final int D6TOTAL = AttributesEnum.D6Total.index();
    public static final int D7TOTAL = AttributesEnum.D7Total.index();
    public static final int D8TOTAL = AttributesEnum.D8Total.index();
    public static final int D9TOTAL = AttributesEnum.D9Total.index();
    public static final int D10TOTAL = AttributesEnum.D10Total.index();
    public static final int D11TOTAL = AttributesEnum.D11Total.index();
    public static final int D12TOTAL = AttributesEnum.D12Total.index();
    public static final int D13TOTAL = AttributesEnum.D13Total.index();
    public static final int D14TOTAL = AttributesEnum.D14Total.index();
    public static final int D15TOTAL = AttributesEnum.D15Total.index();
    public static final int D16TOTAL = AttributesEnum.D16Total.index();
    public static final int D17TOTAL = AttributesEnum.D17Total.index();
    public static final int D18TOTAL = AttributesEnum.D18Total.index();
    public static final int D19TOTAL = AttributesEnum.D19Total.index();
    public static final int D20TOTAL = AttributesEnum.D20Total.index();
    public static final int D21TOTAL = AttributesEnum.D21Total.index();
    public static final int D22TOTAL = AttributesEnum.D22Total.index();
    public static final int D23TOTAL = AttributesEnum.D23Total.index();
    public static final int D24TOTAL = AttributesEnum.D24Total.index();
    public static final int D25TOTAL = AttributesEnum.D25Total.index();
    public static final int D26TOTAL = AttributesEnum.D26Total.index();
    public static final int D27TOTAL = AttributesEnum.D27Total.index();
    public static final int D28TOTAL = AttributesEnum.D28Total.index();
    public static final int D29TOTAL = AttributesEnum.D29Total.index();
    public static final int D30TOTAL = AttributesEnum.D30Total.index();
    public static final int D31TOTAL = AttributesEnum.D31Total.index();
    public static final int MONTHLYGRANDTOTAL = AttributesEnum.MonthlyGrandTotal.index();
    public static final int AVERAGEPERDAY = AttributesEnum.AveragePerDay.index();
    public static final int MONTHSEARCHVO = AttributesEnum.MonthSearchVO.index();
    public static final int WPPLANNINGBOARDVO = AttributesEnum.WpPlanningBoardVO.index();
    public static final int WPPLANNINGBOARDLOADVO = AttributesEnum.WpPlanningBoardLoadVO.index();
    public static final int WPHOLIDAYCALENDARVO = AttributesEnum.WpHolidayCalendarVO.index();
    public static final int BUYERWISEMONTHLYQTYVO = AttributesEnum.BuyerWiseMonthlyQtyVO.index();
    public static final int PRODUCTIONUNITWISEMONTHLYQTYVO = AttributesEnum.ProductionUnitWiseMonthlyQtyVO.index();
    public static final int WPPLANNINGBOARDALLSECTIONLOADVO = AttributesEnum.WpPlanningBoardAllSectionLoadVO.index();
    public static final int MONTHWISEDAILYPROCESSQTYVO = AttributesEnum.MonthWiseDailyProcessQtyVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpMonthListVORowImpl() {
    }
    
    AppModuleImpl appM = getAppModuleImpl();

    public AppModuleImpl getAppModuleImpl() {
        DCBindingContainer bindingContainer =
            (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
        //BindingContext bindingContext = BindingContext.getCurrent();
        DCDataControl dc =
            bindingContainer.findDataControl("AppModuleDataControl"); // Name of application module in datacontrolBinding.cpx
        AppModuleImpl appM = (AppModuleImpl)dc.getDataProvider();
        return appM;
    }



    /**
     * Gets WpMonthListEO entity object.
     * @return the WpMonthListEO
     */
    public WpMonthListEOImpl getWpMonthListEO() {
        return (WpMonthListEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for MONTH_ID using the alias name MonthId.
     * @return the MONTH_ID
     */
    public Number getMonthId() {
        return (Number) getAttributeInternal(MONTHID);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_ID using the alias name MonthId.
     * @param value value to set the MONTH_ID
     */
    public void setMonthId(Number value) {
        setAttributeInternal(MONTHID, value);
    }

    /**
     * Gets the attribute value for MONTH_NAME using the alias name MonthName.
     * @return the MONTH_NAME
     */
    public String getMonthName() {
        return (String) getAttributeInternal(MONTHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_NAME using the alias name MonthName.
     * @param value value to set the MONTH_NAME
     */
    public void setMonthName(String value) {
        setAttributeInternal(MONTHNAME, value);
    }

    /**
     * Gets the attribute value for YEAR using the alias name Year.
     * @return the YEAR
     */
    public Number getYear() {
        return (Number) getAttributeInternal(YEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR using the alias name Year.
     * @param value value to set the YEAR
     */
    public void setYear(Number value) {
        setAttributeInternal(YEAR, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for WEEKLY_HOLIDAY using the alias name WeeklyHoliday.
     * @return the WEEKLY_HOLIDAY
     */
    public String getWeeklyHoliday() {
        return (String) getAttributeInternal(WEEKLYHOLIDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEKLY_HOLIDAY using the alias name WeeklyHoliday.
     * @param value value to set the WEEKLY_HOLIDAY
     */
    public void setWeeklyHoliday(String value) {
        setAttributeInternal(WEEKLYHOLIDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NumberOfDays.
     * @return the NumberOfDays
     */
    public Number getNumberOfDays() {
        return (Number) getAttributeInternal(NUMBEROFDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NumberOfDays.
     * @param value value to set the  NumberOfDays
     */
    public void setNumberOfDays(Number value) {
        setAttributeInternal(NUMBEROFDAYS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WorkingdayCount.
     * @return the WorkingdayCount
     */
    public Number getWorkingdayCount() {
        return (Number) getAttributeInternal(WORKINGDAYCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WorkingdayCount.
     * @param value value to set the  WorkingdayCount
     */
    public void setWorkingdayCount(Number value) {
        setAttributeInternal(WORKINGDAYCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HolidayCount.
     * @return the HolidayCount
     */
    public Number getHolidayCount() {
        return (Number) getAttributeInternal(HOLIDAYCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HolidayCount.
     * @param value value to set the  HolidayCount
     */
    public void setHolidayCount(Number value) {
        setAttributeInternal(HOLIDAYCOUNT, value);
    }


    /**
     * Gets the attribute value for the calculated attribute D1Total.
     * @return the D1Total
     */
    public Number getD1Total() {
       
         return getTotalforAttribute("D1");        
     //   return (Number) getAttributeInternal(D1TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D1Total.
     * @param value value to set the  D1Total
     */
    public void setD1Total(Number value) {
        setAttributeInternal(D1TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D2Total.
     * @return the D2Total
     */
    public Number getD2Total() {
        return getTotalforAttribute("D2");    
       // return (Number) getAttributeInternal(D2TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D2Total.
     * @param value value to set the  D2Total
     */
    public void setD2Total(Number value) {
        setAttributeInternal(D2TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D3Total.
     * @return the D3Total
     */
    public Number getD3Total() {
        return getTotalforAttribute("D3");    
       // return (Number) getAttributeInternal(D3TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D3Total.
     * @param value value to set the  D3Total
     */
    public void setD3Total(Number value) {
        setAttributeInternal(D3TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D4Total.
     * @return the D4Total
     */
    public Number getD4Total() {
        return getTotalforAttribute("D4");   
       // return (Number) getAttributeInternal(D4TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D4Total.
     * @param value value to set the  D4Total
     */
    public void setD4Total(Number value) {
        setAttributeInternal(D4TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D5Total.
     * @return the D5Total
     */
    public Number getD5Total() {
        return getTotalforAttribute("D5");   
      //  return (Number) getAttributeInternal(D5TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D5Total.
     * @param value value to set the  D5Total
     */
    public void setD5Total(Number value) {
        setAttributeInternal(D5TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D6Total.
     * @return the D6Total
     */
    public Number getD6Total() {
        return getTotalforAttribute("D6");   
       // return (Number) getAttributeInternal(D6TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D6Total.
     * @param value value to set the  D6Total
     */
    public void setD6Total(Number value) {
        setAttributeInternal(D6TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D7Total.
     * @return the D7Total
     */
    public Number getD7Total() {
        
        return getTotalforAttribute("D7");   
      //  return (Number) getAttributeInternal(D7TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D7Total.
     * @param value value to set the  D7Total
     */
    public void setD7Total(Number value) {
        setAttributeInternal(D7TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D8Total.
     * @return the D8Total
     */
    public Number getD8Total() {
        return getTotalforAttribute("D8");   
       // return (Number) getAttributeInternal(D8TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D8Total.
     * @param value value to set the  D8Total
     */
    public void setD8Total(Number value) {
        setAttributeInternal(D8TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D9Total.
     * @return the D9Total
     */
    public Number getD9Total() {
        return getTotalforAttribute("D9");   
       // return (Number) getAttributeInternal(D9TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D9Total.
     * @param value value to set the  D9Total
     */
    public void setD9Total(Number value) {
        setAttributeInternal(D9TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D10Total.
     * @return the D10Total
     */
    public Number getD10Total() {
        return getTotalforAttribute("D10");   
      //  return (Number) getAttributeInternal(D10TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D10Total.
     * @param value value to set the  D10Total
     */
    public void setD10Total(Number value) {
        setAttributeInternal(D10TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D11Total.
     * @return the D11Total
     */
    public Number getD11Total() {
        return getTotalforAttribute("D11");   
        //return (Number) getAttributeInternal(D11TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D11Total.
     * @param value value to set the  D11Total
     */
    public void setD11Total(Number value) {
        setAttributeInternal(D11TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D12Total.
     * @return the D12Total
     */
    public Number getD12Total() {
        return getTotalforAttribute("D12");   
        //return (Number) getAttributeInternal(D12TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D12Total.
     * @param value value to set the  D12Total
     */
    public void setD12Total(Number value) {
        setAttributeInternal(D12TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D13Total.
     * @return the D13Total
     */
    public Number getD13Total() {
      return getTotalforAttribute("D13");   
      //  return (Number) getAttributeInternal(D13TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D13Total.
     * @param value value to set the  D13Total
     */
    public void setD13Total(Number value) {
        
        setAttributeInternal(D13TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D14Total.
     * @return the D14Total
     */
    public Number getD14Total() {
        return getTotalforAttribute("D14");   
        //return (Number) getAttributeInternal(D14TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D14Total.
     * @param value value to set the  D14Total
     */
    public void setD14Total(Number value) {
        setAttributeInternal(D14TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D15Total.
     * @return the D15Total
     */
    public Number getD15Total() {
        return getTotalforAttribute("D15");   
        //return (Number) getAttributeInternal(D15TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D15Total.
     * @param value value to set the  D15Total
     */
    public void setD15Total(Number value) {
        setAttributeInternal(D15TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D16Total.
     * @return the D16Total
     */
    public Number getD16Total() {
        return getTotalforAttribute("D16");   
       // return (Number) getAttributeInternal(D16TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D16Total.
     * @param value value to set the  D16Total
     */
    public void setD16Total(Number value) {
        setAttributeInternal(D16TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D17Total.
     * @return the D17Total
     */
    public Number getD17Total() {
        
        return getTotalforAttribute("D17");   
       // return (Number) getAttributeInternal(D17TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D17Total.
     * @param value value to set the  D17Total
     */
    public void setD17Total(Number value) {
        setAttributeInternal(D17TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D18Total.
     * @return the D18Total
     */
    public Number getD18Total() {
       
        return getTotalforAttribute("D18");   
        //return (Number) getAttributeInternal(D18TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D18Total.
     * @param value value to set the  D18Total
     */
    public void setD18Total(Number value) {
        setAttributeInternal(D18TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D19Total.
     * @return the D19Total
     */
    public Number getD19Total() {
        return getTotalforAttribute("D19");   
      //  return (Number) getAttributeInternal(D19TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D19Total.
     * @param value value to set the  D19Total
     */
    public void setD19Total(Number value) {
        setAttributeInternal(D19TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D20Total.
     * @return the D20Total
     */
    public Number getD20Total() {
        
        return getTotalforAttribute("D20");    
       // return (Number) getAttributeInternal(D20TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D20Total.
     * @param value value to set the  D20Total
     */
    public void setD20Total(Number value) {
        setAttributeInternal(D20TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D21Total.
     * @return the D21Total
     */
    public Number getD21Total() {
        return getTotalforAttribute("D21");   
        //return (Number) getAttributeInternal(D21TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D21Total.
     * @param value value to set the  D21Total
     */
    public void setD21Total(Number value) {
        setAttributeInternal(D21TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D22Total.
     * @return the D22Total
     */
    public Number getD22Total() {
        return getTotalforAttribute("D22");   
        //return (Number) getAttributeInternal(D22TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D22Total.
     * @param value value to set the  D22Total
     */
    public void setD22Total(Number value) {
        setAttributeInternal(D22TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D23Total.
     * @return the D23Total
     */
    public Number getD23Total() {
        return getTotalforAttribute("D23");   
      //  return (Number) getAttributeInternal(D23TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D23Total.
     * @param value value to set the  D23Total
     */
    public void setD23Total(Number value) {
        setAttributeInternal(D23TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D24Total.
     * @return the D24Total
     */
    public Number getD24Total() {
        return getTotalforAttribute("D24");   
       // return (Number) getAttributeInternal(D24TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D24Total.
     * @param value value to set the  D24Total
     */
    public void setD24Total(Number value) {
        setAttributeInternal(D24TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D25Total.
     * @return the D25Total
     */
    public Number getD25Total() {
        return getTotalforAttribute("D25");   
       // return (Number) getAttributeInternal(D25TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D25Total.
     * @param value value to set the  D25Total
     */
    public void setD25Total(Number value) {
        setAttributeInternal(D25TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D26Total.
     * @return the D26Total
     */
    public Number getD26Total() {
        return getTotalforAttribute("D26");   
   //     return (Number) getAttributeInternal(D26TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D26Total.
     * @param value value to set the  D26Total
     */
    public void setD26Total(Number value) {
        setAttributeInternal(D26TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D27Total.
     * @return the D27Total
     */
    public Number getD27Total() {
        return getTotalforAttribute("D27");   
        //return (Number) getAttributeInternal(D27TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D27Total.
     * @param value value to set the  D27Total
     */
    public void setD27Total(Number value) {
        setAttributeInternal(D27TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D28Total.
     * @return the D28Total
     */
    public Number getD28Total() {
        return getTotalforAttribute("D28");   
      //  return (Number) getAttributeInternal(D28TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D28Total.
     * @param value value to set the  D28Total
     */
    public void setD28Total(Number value) {
        setAttributeInternal(D28TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D29Total.
     * @return the D29Total
     */
    public Number getD29Total() {
        return getTotalforAttribute("D29");   
     //   return (Number) getAttributeInternal(D29TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D29Total.
     * @param value value to set the  D29Total
     */
    public void setD29Total(Number value) {
        setAttributeInternal(D29TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D30Total.
     * @return the D30Total
     */
    public Number getD30Total() {
        return getTotalforAttribute("D30");   
       // return (Number) getAttributeInternal(D30TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D30Total.
     * @param value value to set the  D30Total
     */
    public void setD30Total(Number value) {
        setAttributeInternal(D30TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D31Total.
     * @return the D31Total
     */
    public Number getD31Total() {
        return getTotalforAttribute("D31");   
     //   return (Number) getAttributeInternal(D31TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D31Total.
     * @param value value to set the  D31Total
     */
    public void setD31Total(Number value) {
        setAttributeInternal(D31TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthlyGrandTotal.
     * @return the MonthlyGrandTotal
     */
    public Number getMonthlyGrandTotal() {
        return getTotalforAttribute("MonthlyTotal");   
        
      //  return (String) getAttributeInternal(MONTHLYGRANDTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthlyGrandTotal.
     * @param value value to set the  MonthlyGrandTotal
     */
    public void setMonthlyGrandTotal(Number value) {
        setAttributeInternal(MONTHLYGRANDTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AveragePerDay.
     * @return the AveragePerDay
     */
    public Number getAveragePerDay() {
        return (Number) getAttributeInternal(AVERAGEPERDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AveragePerDay.
     * @param value value to set the  AveragePerDay
     */
    public void setAveragePerDay(Number value) {
        setAttributeInternal(AVERAGEPERDAY, value);
    }


    /**
     * Gets the attribute value for MONTH_SERIAL using the alias name MonthSerial.
     * @return the MONTH_SERIAL
     */
    public Number getMonthSerial() {
        return (Number) getAttributeInternal(MONTHSERIAL);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_SERIAL using the alias name MonthSerial.
     * @param value value to set the MONTH_SERIAL
     */
    public void setMonthSerial(Number value) {
        setAttributeInternal(MONTHSERIAL, value);
    }

    /**
     * Gets the attribute value for MONTH_NUMBER using the alias name MonthNumber.
     * @return the MONTH_NUMBER
     */
    public Number getMonthNumber() {
        return (Number) getAttributeInternal(MONTHNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_NUMBER using the alias name MonthNumber.
     * @param value value to set the MONTH_NUMBER
     */
    public void setMonthNumber(Number value) {
        setAttributeInternal(MONTHNUMBER, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link MonthSearchVO.
     */
    public Row getMonthSearchVO() {
        return (Row)getAttributeInternal(MONTHSEARCHVO);
    }

    /**
     * Sets the master-detail link MonthSearchVO between this object and <code>value</code>.
     */
    public void setMonthSearchVO(Row value) {
        setAttributeInternal(MONTHSEARCHVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpPlanningBoardVO.
     */
    public RowIterator getWpPlanningBoardVO() {
        return (RowIterator)getAttributeInternal(WPPLANNINGBOARDVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpPlanningBoardLoadVO.
     */
    public RowIterator getWpPlanningBoardLoadVO() {
        return (RowIterator)getAttributeInternal(WPPLANNINGBOARDLOADVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpHolidayCalendarVO.
     */
    public RowIterator getWpHolidayCalendarVO() {
        return (RowIterator)getAttributeInternal(WPHOLIDAYCALENDARVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BuyerWiseMonthlyQtyVO.
     */
    public RowIterator getBuyerWiseMonthlyQtyVO() {
        return (RowIterator)getAttributeInternal(BUYERWISEMONTHLYQTYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProductionUnitWiseMonthlyQtyVO.
     */
    public RowIterator getProductionUnitWiseMonthlyQtyVO() {
        return (RowIterator)getAttributeInternal(PRODUCTIONUNITWISEMONTHLYQTYVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WpPlanningBoardAllSectionLoadVO.
     */
    public RowIterator getWpPlanningBoardAllSectionLoadVO() {
        return (RowIterator)getAttributeInternal(WPPLANNINGBOARDALLSECTIONLOADVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MonthWiseDailyProcessQtyVO.
     */
    public RowIterator getMonthWiseDailyProcessQtyVO() {
        return (RowIterator)getAttributeInternal(MONTHWISEDAILYPROCESSQTYVO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    
    public void  updateLoadRowEntry(){
        String currentMonthId = this.getMonthId().toString();          
        String statement = "BEGIN APPS.WP_UPDATE_LOAD_ROW_ENTRY(:1); END;";
        CallableStatement cs =  appM.getDBTransaction().createCallableStatement(statement, 1);
          
        try {
            cs.setInt(1, Integer.parseInt(currentMonthId));
            cs.execute();
        }
        catch(Exception e){
           e.printStackTrace() ;
        }    
        
    }
    
}
