package model.view;

import model.entity.WpPlanningBoardEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 08 17:46:28 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpPlanningBoardVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        PlanningBoardId {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getPlanningBoardId();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setPlanningBoardId((Number)value);
            }
        }
        ,
        MonthId {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getMonthId();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setMonthId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        D1 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD1();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD1((Number)value);
            }
        }
        ,
        D2 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD2();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD2((Number)value);
            }
        }
        ,
        D3 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD3();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD3((Number)value);
            }
        }
        ,
        D4 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD4();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD4((Number)value);
            }
        }
        ,
        D5 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD5();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD5((Number)value);
            }
        }
        ,
        D6 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD6();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD6((Number)value);
            }
        }
        ,
        D7 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD7();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD7((Number)value);
            }
        }
        ,
        D8 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD8();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD8((Number)value);
            }
        }
        ,
        D9 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD9();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD9((Number)value);
            }
        }
        ,
        D10 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD10();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD10((Number)value);
            }
        }
        ,
        D11 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD11();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD11((Number)value);
            }
        }
        ,
        D12 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD12();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD12((Number)value);
            }
        }
        ,
        D13 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD13();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD13((Number)value);
            }
        }
        ,
        D14 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD14();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD14((Number)value);
            }
        }
        ,
        D15 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD15();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD15((Number)value);
            }
        }
        ,
        D16 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD16();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD16((Number)value);
            }
        }
        ,
        D17 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD17();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD17((Number)value);
            }
        }
        ,
        D18 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD18();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD18((Number)value);
            }
        }
        ,
        D19 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD19();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD19((Number)value);
            }
        }
        ,
        D20 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD20();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD20((Number)value);
            }
        }
        ,
        D21 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD21();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD21((Number)value);
            }
        }
        ,
        D22 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD22();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD22((Number)value);
            }
        }
        ,
        D23 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD23();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD23((Number)value);
            }
        }
        ,
        D24 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD24();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD24((Number)value);
            }
        }
        ,
        D25 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD25();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD25((Number)value);
            }
        }
        ,
        D26 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD26();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD26((Number)value);
            }
        }
        ,
        D27 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD27();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD27((Number)value);
            }
        }
        ,
        D28 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD28();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD28((Number)value);
            }
        }
        ,
        D29 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD29();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD29((Number)value);
            }
        }
        ,
        D30 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD30();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD30((Number)value);
            }
        }
        ,
        D31 {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getD31();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setD31((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        MonthlyTotal {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getMonthlyTotal();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setMonthlyTotal((Number)value);
            }
        }
        ,
        LcUnit {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getLcUnit();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setLcUnit((Number)value);
            }
        }
        ,
        LcUnitName {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getLcUnitName();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setLcUnitName((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BuyerName {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        Season {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Style {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Color {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getColor();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        WashName {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getWashName();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        ProductionUnit {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getProductionUnit();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setProductionUnit((Number)value);
            }
        }
        ,
        ProductionUnitName {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getProductionUnitName();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setProductionUnitName((String)value);
            }
        }
        ,
        OrderQty {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        CurrentSamVersion {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getCurrentSamVersion();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setCurrentSamVersion((Number)value);
            }
        }
        ,
        AvailableSamVersion {
            public Object get(WpPlanningBoardVORowImpl obj) {
                return obj.getAvailableSamVersion();
            }

            public void put(WpPlanningBoardVORowImpl obj, Object value) {
                obj.setAvailableSamVersion((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WpPlanningBoardVORowImpl object);

        public abstract void put(WpPlanningBoardVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PLANNINGBOARDID = AttributesEnum.PlanningBoardId.index();
    public static final int MONTHID = AttributesEnum.MonthId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int D1 = AttributesEnum.D1.index();
    public static final int D2 = AttributesEnum.D2.index();
    public static final int D3 = AttributesEnum.D3.index();
    public static final int D4 = AttributesEnum.D4.index();
    public static final int D5 = AttributesEnum.D5.index();
    public static final int D6 = AttributesEnum.D6.index();
    public static final int D7 = AttributesEnum.D7.index();
    public static final int D8 = AttributesEnum.D8.index();
    public static final int D9 = AttributesEnum.D9.index();
    public static final int D10 = AttributesEnum.D10.index();
    public static final int D11 = AttributesEnum.D11.index();
    public static final int D12 = AttributesEnum.D12.index();
    public static final int D13 = AttributesEnum.D13.index();
    public static final int D14 = AttributesEnum.D14.index();
    public static final int D15 = AttributesEnum.D15.index();
    public static final int D16 = AttributesEnum.D16.index();
    public static final int D17 = AttributesEnum.D17.index();
    public static final int D18 = AttributesEnum.D18.index();
    public static final int D19 = AttributesEnum.D19.index();
    public static final int D20 = AttributesEnum.D20.index();
    public static final int D21 = AttributesEnum.D21.index();
    public static final int D22 = AttributesEnum.D22.index();
    public static final int D23 = AttributesEnum.D23.index();
    public static final int D24 = AttributesEnum.D24.index();
    public static final int D25 = AttributesEnum.D25.index();
    public static final int D26 = AttributesEnum.D26.index();
    public static final int D27 = AttributesEnum.D27.index();
    public static final int D28 = AttributesEnum.D28.index();
    public static final int D29 = AttributesEnum.D29.index();
    public static final int D30 = AttributesEnum.D30.index();
    public static final int D31 = AttributesEnum.D31.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int MONTHLYTOTAL = AttributesEnum.MonthlyTotal.index();
    public static final int LCUNIT = AttributesEnum.LcUnit.index();
    public static final int LCUNITNAME = AttributesEnum.LcUnitName.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int PRODUCTIONUNIT = AttributesEnum.ProductionUnit.index();
    public static final int PRODUCTIONUNITNAME = AttributesEnum.ProductionUnitName.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CURRENTSAMVERSION = AttributesEnum.CurrentSamVersion.index();
    public static final int AVAILABLESAMVERSION = AttributesEnum.AvailableSamVersion.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WpPlanningBoardVORowImpl() {
    }

    /**
     * Gets WpPlanningBoardEO entity object.
     * @return the WpPlanningBoardEO
     */
    public WpPlanningBoardEOImpl getWpPlanningBoardEO() {
        return (WpPlanningBoardEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PLANNING_BOARD_ID using the alias name PlanningBoardId.
     * @return the PLANNING_BOARD_ID
     */
    public Number getPlanningBoardId() {
        return (Number) getAttributeInternal(PLANNINGBOARDID);
    }

    /**
     * Sets <code>value</code> as attribute value for PLANNING_BOARD_ID using the alias name PlanningBoardId.
     * @param value value to set the PLANNING_BOARD_ID
     */
    public void setPlanningBoardId(Number value) {
        setAttributeInternal(PLANNINGBOARDID, value);
    }

    /**
     * Gets the attribute value for MONTH_ID using the alias name MonthId.
     * @return the MONTH_ID
     */
    public Number getMonthId() {
        return (Number) getAttributeInternal(MONTHID);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH_ID using the alias name MonthId.
     * @param value value to set the MONTH_ID
     */
    public void setMonthId(Number value) {
        setAttributeInternal(MONTHID, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for D1 using the alias name D1.
     * @return the D1
     */
    public Number getD1() {
        return (Number) getAttributeInternal(D1);
    }

    /**
     * Sets <code>value</code> as attribute value for D1 using the alias name D1.
     * @param value value to set the D1
     */
    public void setD1(Number value) {
        setAttributeInternal(D1, value);
        
        this.setMonthlyTotal(this.getMonthlyTotal());
        
     
  
    }

    /**
     * Gets the attribute value for D2 using the alias name D2.
     * @return the D2
     */
    public Number getD2() {
        return (Number) getAttributeInternal(D2);
    }

    /**
     * Sets <code>value</code> as attribute value for D2 using the alias name D2.
     * @param value value to set the D2
     */
    public void setD2(Number value) {
        setAttributeInternal(D2, value);
    }

    /**
     * Gets the attribute value for D3 using the alias name D3.
     * @return the D3
     */
    public Number getD3() {
        return (Number) getAttributeInternal(D3);
    }

    /**
     * Sets <code>value</code> as attribute value for D3 using the alias name D3.
     * @param value value to set the D3
     */
    public void setD3(Number value) {
        setAttributeInternal(D3, value);
    }

    /**
     * Gets the attribute value for D4 using the alias name D4.
     * @return the D4
     */
    public Number getD4() {
        return (Number) getAttributeInternal(D4);
    }

    /**
     * Sets <code>value</code> as attribute value for D4 using the alias name D4.
     * @param value value to set the D4
     */
    public void setD4(Number value) {
        setAttributeInternal(D4, value);
    }

    /**
     * Gets the attribute value for D5 using the alias name D5.
     * @return the D5
     */
    public Number getD5() {
        return (Number) getAttributeInternal(D5);
    }

    /**
     * Sets <code>value</code> as attribute value for D5 using the alias name D5.
     * @param value value to set the D5
     */
    public void setD5(Number value) {
        setAttributeInternal(D5, value);
    }

    /**
     * Gets the attribute value for D6 using the alias name D6.
     * @return the D6
     */
    public Number getD6() {
        return (Number) getAttributeInternal(D6);
    }

    /**
     * Sets <code>value</code> as attribute value for D6 using the alias name D6.
     * @param value value to set the D6
     */
    public void setD6(Number value) {
        setAttributeInternal(D6, value);
    }

    /**
     * Gets the attribute value for D7 using the alias name D7.
     * @return the D7
     */
    public Number getD7() {
        return (Number) getAttributeInternal(D7);
    }

    /**
     * Sets <code>value</code> as attribute value for D7 using the alias name D7.
     * @param value value to set the D7
     */
    public void setD7(Number value) {
        setAttributeInternal(D7, value);
    }

    /**
     * Gets the attribute value for D8 using the alias name D8.
     * @return the D8
     */
    public Number getD8() {
        return (Number) getAttributeInternal(D8);
    }

    /**
     * Sets <code>value</code> as attribute value for D8 using the alias name D8.
     * @param value value to set the D8
     */
    public void setD8(Number value) {
        setAttributeInternal(D8, value);
    }

    /**
     * Gets the attribute value for D9 using the alias name D9.
     * @return the D9
     */
    public Number getD9() {
        return (Number) getAttributeInternal(D9);
    }

    /**
     * Sets <code>value</code> as attribute value for D9 using the alias name D9.
     * @param value value to set the D9
     */
    public void setD9(Number value) {
        setAttributeInternal(D9, value);
    }

    /**
     * Gets the attribute value for D10 using the alias name D10.
     * @return the D10
     */
    public Number getD10() {
        return (Number) getAttributeInternal(D10);
    }

    /**
     * Sets <code>value</code> as attribute value for D10 using the alias name D10.
     * @param value value to set the D10
     */
    public void setD10(Number value) {
        setAttributeInternal(D10, value);
    }

    /**
     * Gets the attribute value for D11 using the alias name D11.
     * @return the D11
     */
    public Number getD11() {
        return (Number) getAttributeInternal(D11);
    }

    /**
     * Sets <code>value</code> as attribute value for D11 using the alias name D11.
     * @param value value to set the D11
     */
    public void setD11(Number value) {
        setAttributeInternal(D11, value);
    }

    /**
     * Gets the attribute value for D12 using the alias name D12.
     * @return the D12
     */
    public Number getD12() {
        return (Number) getAttributeInternal(D12);
    }

    /**
     * Sets <code>value</code> as attribute value for D12 using the alias name D12.
     * @param value value to set the D12
     */
    public void setD12(Number value) {
        setAttributeInternal(D12, value);
    }

    /**
     * Gets the attribute value for D13 using the alias name D13.
     * @return the D13
     */
    public Number getD13() {
        return (Number) getAttributeInternal(D13);
    }

    /**
     * Sets <code>value</code> as attribute value for D13 using the alias name D13.
     * @param value value to set the D13
     */
    public void setD13(Number value) {
        setAttributeInternal(D13, value);
    }

    /**
     * Gets the attribute value for D14 using the alias name D14.
     * @return the D14
     */
    public Number getD14() {
        return (Number) getAttributeInternal(D14);
    }

    /**
     * Sets <code>value</code> as attribute value for D14 using the alias name D14.
     * @param value value to set the D14
     */
    public void setD14(Number value) {
        setAttributeInternal(D14, value);
    }

    /**
     * Gets the attribute value for D15 using the alias name D15.
     * @return the D15
     */
    public Number getD15() {
        return (Number) getAttributeInternal(D15);
    }

    /**
     * Sets <code>value</code> as attribute value for D15 using the alias name D15.
     * @param value value to set the D15
     */
    public void setD15(Number value) {
        setAttributeInternal(D15, value);
    }

    /**
     * Gets the attribute value for D16 using the alias name D16.
     * @return the D16
     */
    public Number getD16() {
        return (Number) getAttributeInternal(D16);
    }

    /**
     * Sets <code>value</code> as attribute value for D16 using the alias name D16.
     * @param value value to set the D16
     */
    public void setD16(Number value) {
        setAttributeInternal(D16, value);
    }

    /**
     * Gets the attribute value for D17 using the alias name D17.
     * @return the D17
     */
    public Number getD17() {
        return (Number) getAttributeInternal(D17);
    }

    /**
     * Sets <code>value</code> as attribute value for D17 using the alias name D17.
     * @param value value to set the D17
     */
    public void setD17(Number value) {
        setAttributeInternal(D17, value);
    }

    /**
     * Gets the attribute value for D18 using the alias name D18.
     * @return the D18
     */
    public Number getD18() {
        return (Number) getAttributeInternal(D18);
    }

    /**
     * Sets <code>value</code> as attribute value for D18 using the alias name D18.
     * @param value value to set the D18
     */
    public void setD18(Number value) {
        setAttributeInternal(D18, value);
    }

    /**
     * Gets the attribute value for D19 using the alias name D19.
     * @return the D19
     */
    public Number getD19() {
        return (Number) getAttributeInternal(D19);
    }

    /**
     * Sets <code>value</code> as attribute value for D19 using the alias name D19.
     * @param value value to set the D19
     */
    public void setD19(Number value) {
        setAttributeInternal(D19, value);
    }

    /**
     * Gets the attribute value for D20 using the alias name D20.
     * @return the D20
     */
    public Number getD20() {
        return (Number) getAttributeInternal(D20);
    }

    /**
     * Sets <code>value</code> as attribute value for D20 using the alias name D20.
     * @param value value to set the D20
     */
    public void setD20(Number value) {
        setAttributeInternal(D20, value);
    }

    /**
     * Gets the attribute value for D21 using the alias name D21.
     * @return the D21
     */
    public Number getD21() {
        return (Number) getAttributeInternal(D21);
    }

    /**
     * Sets <code>value</code> as attribute value for D21 using the alias name D21.
     * @param value value to set the D21
     */
    public void setD21(Number value) {
        setAttributeInternal(D21, value);
    }

    /**
     * Gets the attribute value for D22 using the alias name D22.
     * @return the D22
     */
    public Number getD22() {
        return (Number) getAttributeInternal(D22);
    }

    /**
     * Sets <code>value</code> as attribute value for D22 using the alias name D22.
     * @param value value to set the D22
     */
    public void setD22(Number value) {
        setAttributeInternal(D22, value);
    }

    /**
     * Gets the attribute value for D23 using the alias name D23.
     * @return the D23
     */
    public Number getD23() {
        return (Number) getAttributeInternal(D23);
    }

    /**
     * Sets <code>value</code> as attribute value for D23 using the alias name D23.
     * @param value value to set the D23
     */
    public void setD23(Number value) {
        setAttributeInternal(D23, value);
    }

    /**
     * Gets the attribute value for D24 using the alias name D24.
     * @return the D24
     */
    public Number getD24() {
        return (Number) getAttributeInternal(D24);
    }

    /**
     * Sets <code>value</code> as attribute value for D24 using the alias name D24.
     * @param value value to set the D24
     */
    public void setD24(Number value) {
        setAttributeInternal(D24, value);
    }

    /**
     * Gets the attribute value for D25 using the alias name D25.
     * @return the D25
     */
    public Number getD25() {
        return (Number) getAttributeInternal(D25);
    }

    /**
     * Sets <code>value</code> as attribute value for D25 using the alias name D25.
     * @param value value to set the D25
     */
    public void setD25(Number value) {
        setAttributeInternal(D25, value);
    }

    /**
     * Gets the attribute value for D26 using the alias name D26.
     * @return the D26
     */
    public Number getD26() {
        return (Number) getAttributeInternal(D26);
    }

    /**
     * Sets <code>value</code> as attribute value for D26 using the alias name D26.
     * @param value value to set the D26
     */
    public void setD26(Number value) {
        setAttributeInternal(D26, value);
    }

    /**
     * Gets the attribute value for D27 using the alias name D27.
     * @return the D27
     */
    public Number getD27() {
        return (Number) getAttributeInternal(D27);
    }

    /**
     * Sets <code>value</code> as attribute value for D27 using the alias name D27.
     * @param value value to set the D27
     */
    public void setD27(Number value) {
        setAttributeInternal(D27, value);
    }

    /**
     * Gets the attribute value for D28 using the alias name D28.
     * @return the D28
     */
    public Number getD28() {
        return (Number) getAttributeInternal(D28);
    }

    /**
     * Sets <code>value</code> as attribute value for D28 using the alias name D28.
     * @param value value to set the D28
     */
    public void setD28(Number value) {
        setAttributeInternal(D28, value);
    }

    /**
     * Gets the attribute value for D29 using the alias name D29.
     * @return the D29
     */
    public Number getD29() {
        return (Number) getAttributeInternal(D29);
    }

    /**
     * Sets <code>value</code> as attribute value for D29 using the alias name D29.
     * @param value value to set the D29
     */
    public void setD29(Number value) {
        setAttributeInternal(D29, value);
    }

    /**
     * Gets the attribute value for D30 using the alias name D30.
     * @return the D30
     */
    public Number getD30() {
        return (Number) getAttributeInternal(D30);
    }

    /**
     * Sets <code>value</code> as attribute value for D30 using the alias name D30.
     * @param value value to set the D30
     */
    public void setD30(Number value) {
        setAttributeInternal(D30, value);
    }

    /**
     * Gets the attribute value for D31 using the alias name D31.
     * @return the D31
     */
    public Number getD31() {
        return (Number) getAttributeInternal(D31);
    }

    /**
     * Sets <code>value</code> as attribute value for D31 using the alias name D31.
     * @param value value to set the D31
     */
    public void setD31(Number value) {
        setAttributeInternal(D31, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LcUnit.
     * @return the LcUnit
     */
    public Number getLcUnit() {
        return (Number) getAttributeInternal(LCUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcUnit.
     * @param value value to set the  LcUnit
     */
    public void setLcUnit(Number value) {
        setAttributeInternal(LCUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LcUnitName.
     * @return the LcUnitName
     */
    public String getLcUnitName() {
        return (String) getAttributeInternal(LCUNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcUnitName.
     * @param value value to set the  LcUnitName
     */
    public void setLcUnitName(String value) {
        setAttributeInternal(LCUNITNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Color.
     * @return the Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color.
     * @param value value to set the  Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WashName.
     * @return the WashName
     */
    public String getWashName() {
        return (String) getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WashName.
     * @param value value to set the  WashName
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductionUnit.
     * @return the ProductionUnit
     */
    public Number getProductionUnit() {
        return (Number) getAttributeInternal(PRODUCTIONUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductionUnit.
     * @param value value to set the  ProductionUnit
     */
    public void setProductionUnit(Number value) {
        setAttributeInternal(PRODUCTIONUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductionUnitName.
     * @return the ProductionUnitName
     */
    public String getProductionUnitName() {
        return (String) getAttributeInternal(PRODUCTIONUNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductionUnitName.
     * @param value value to set the  ProductionUnitName
     */
    public void setProductionUnitName(String value) {
        setAttributeInternal(PRODUCTIONUNITNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderQty.
     * @return the OrderQty
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderQty.
     * @param value value to set the  OrderQty
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSamVersion.
     * @return the CurrentSamVersion
     */
    public Number getCurrentSamVersion() {
        return (Number) getAttributeInternal(CURRENTSAMVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSamVersion.
     * @param value value to set the  CurrentSamVersion
     */
    public void setCurrentSamVersion(Number value) {
        setAttributeInternal(CURRENTSAMVERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AvailableSamVersion.
     * @return the AvailableSamVersion
     */
    public Number getAvailableSamVersion() {
        return (Number) getAttributeInternal(AVAILABLESAMVERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AvailableSamVersion.
     * @param value value to set the  AvailableSamVersion
     */
    public void setAvailableSamVersion(Number value) {
        setAttributeInternal(AVAILABLESAMVERSION, value);
    }

    /**
     * Gets the attribute value for MONTHLY_TOTAL using the alias name MonthlyTotal.
     * @return the MONTHLY_TOTAL
     */
    public Number getMonthlyTotal() {
        Number total = new Number(0);
        String dayName = null;
            for (int i=1;i<=31; i++  ){
                dayName = "D"+i;
                
                if(this.getAttribute(dayName) != null){
                    total  = total.add((Number)this.getAttribute(dayName));
                  //  System.out.println("============ "+dayName + "  total  "+total);
                }

            }        
        return total;
     
        
    //  return (Number) getAttributeInternal(MONTHLYTOTAL);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTHLY_TOTAL using the alias name MonthlyTotal.
     * @param value value to set the MONTHLY_TOTAL
     */
    public void setMonthlyTotal(Number value) {
       
        Number total = new Number(0);
        String dayName = null;
            for (int i=1;i<=31; i++  ){
                dayName = "D"+i;
                
                if(this.getAttribute(dayName) != null){
                    total  = total.add((Number)this.getAttribute(dayName));
                  //  System.out.println("============ "+dayName + "  total  "+total);
                }

            }        

        
        
        
        
        setAttributeInternal(MONTHLYTOTAL,total);
        
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
